server:
  port: 8083
spring:
  application:
    name: app-producer-01
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    #feign 日志以什么样的级别监控该接口
    org.example.controller: debug